import os
from PyQt5 import QtCore, QtGui, QtWidgets

class api_install_reference(object):
    def setupUi(self, api_install_reference):
        api_install_reference.setObjectName("api_install_reference")
        api_install_reference.resize(577, 189)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("%s/Icons/mysql_logo.png"%(os.getcwd())), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        api_install_reference.setWindowIcon(icon)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(api_install_reference)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(api_install_reference)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(api_install_reference)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(api_install_reference)
        font = QtGui.QFont()
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(19, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(api_install_reference)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(api_install_reference)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(368, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(api_install_reference)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(api_install_reference)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)

        self.retranslateUi(api_install_reference)
        QtCore.QMetaObject.connectSlotsByName(api_install_reference)

    def retranslateUi(self, api_install_reference):
        api_install_reference.setWindowTitle(QtCore.QCoreApplication.translate("api_install_reference", "Installing MySQL API", None))
        self.label.setText(QtCore.QCoreApplication.translate("api_install_reference", "The API(Application Programming Interface) Driver for  is currently not installed, to install please download ", None))
        self.label_2.setText(QtCore.QCoreApplication.translate("api_install_reference", "Debian API package:", None))
        self.label_3.setText(QtCore.QCoreApplication.translate("api_install_reference", "", None))
        self.label_4.setText(QtCore.QCoreApplication.translate("api_install_reference", "Reference from pythons wiki page:", None))
        self.label_5.setText(QtCore.QCoreApplication.translate("api_install_reference", "", None))
        self.label_6.setText(QtCore.QCoreApplication.translate("api_install_reference", "Windows API Drivers could be downloaded from the above python referenced page", None))
        self.label_7.setText(QtCore.QCoreApplication.translate("api_install_reference", "", None))
