import os
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_bruteforce_attack_dialog(object):
    def setupUi(self, bruteforce_attack_dialog):
        bruteforce_attack_dialog.setObjectName("bruteforce_attack_dialog")
        bruteforce_attack_dialog.resize(630, 648)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(bruteforce_attack_dialog.sizePolicy().hasHeightForWidth())
        bruteforce_attack_dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        bruteforce_attack_dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/bruteforce.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        bruteforce_attack_dialog.setWindowIcon(icon)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(bruteforce_attack_dialog)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 95, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.attack_server_label = QtWidgets.QLabel(bruteforce_attack_dialog)
        self.attack_server_label.setText("")
        self.attack_server_label.setPixmap(QtGui.QPixmap("%s/Icons/mysql_logo.png"%(os.getcwd())))
        self.attack_server_label.setObjectName("attack_server_label")
        self.horizontalLayout_4.addWidget(self.attack_server_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.groupBox = QtWidgets.QGroupBox(bruteforce_attack_dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mysql_radio = QtWidgets.QRadioButton(self.groupBox)
        self.mysql_radio.setChecked(True)
        self.mysql_radio.setObjectName("mysql_radio")
        self.horizontalLayout_3.addWidget(self.mysql_radio)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.oracle_radio = QtWidgets.QRadioButton(self.groupBox)
        self.oracle_radio.setObjectName("oracle_radio")
        self.horizontalLayout_3.addWidget(self.oracle_radio)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.postgres_radio = QtWidgets.QRadioButton(self.groupBox)
        self.postgres_radio.setObjectName("postgres_radio")
        self.horizontalLayout_3.addWidget(self.postgres_radio)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.mssql_radio = QtWidgets.QRadioButton(self.groupBox)
        self.mssql_radio.setObjectName("mssql_radio")
        self.horizontalLayout_3.addWidget(self.mssql_radio)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_9.addWidget(self.groupBox)
        spacerItem8 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem8)
        self.groupBox_3 = QtWidgets.QGroupBox(bruteforce_attack_dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.attck_server_checkbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.attck_server_checkbox.setObjectName("attck_server_checkbox")
        self.verticalLayout_2.addWidget(self.attck_server_checkbox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.attack_server_linedit = QtWidgets.QLineEdit(self.groupBox_3)
        self.attack_server_linedit.setObjectName("attack_server_linedit")
        self.verticalLayout.addWidget(self.attack_server_linedit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.attack_port_linedit = QtWidgets.QLineEdit(self.groupBox_3)
        self.attack_port_linedit.setObjectName("attack_port_linedit")
        self.horizontalLayout.addWidget(self.attack_port_linedit)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem10 = QtWidgets.QSpacerItem(46, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        spacerItem11 = QtWidgets.QSpacerItem(23, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem11)
        self.groupBox_2 = QtWidgets.QGroupBox(bruteforce_attack_dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.userlist_button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.userlist_button.sizePolicy().hasHeightForWidth())
        self.userlist_button.setSizePolicy(sizePolicy)
        self.userlist_button.setBaseSize(QtCore.QSize(9, 0))
        self.userlist_button.setIconSize(QtCore.QSize(30, 32))
        self.userlist_button.setObjectName("userlist_button")
        self.verticalLayout_7.addWidget(self.userlist_button)
        self.userlist_details = QtWidgets.QLabel(self.groupBox_2)
        self.userlist_details.setAlignment(QtCore.Qt.AlignCenter)
        self.userlist_details.setObjectName("userlist_details")
        self.verticalLayout_7.addWidget(self.userlist_details)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.blank_password_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.blank_password_checkbox.setObjectName("blank_password_checkbox")
        self.horizontalLayout_7.addWidget(self.blank_password_checkbox)
        spacerItem12 = QtWidgets.QSpacerItem(0, 81, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.wordlist_button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.wordlist_button.sizePolicy().hasHeightForWidth())
        self.wordlist_button.setSizePolicy(sizePolicy)
        self.wordlist_button.setObjectName("wordlist_button")
        self.verticalLayout_6.addWidget(self.wordlist_button)
        self.wordlist_details = QtWidgets.QLabel(self.groupBox_2)
        self.wordlist_details.setAlignment(QtCore.Qt.AlignCenter)
        self.wordlist_details.setObjectName("wordlist_details")
        self.verticalLayout_6.addWidget(self.wordlist_details)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_7)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem13 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.current_userlist = QtWidgets.QLabel(bruteforce_attack_dialog)
        self.current_userlist.setAlignment(QtCore.Qt.AlignCenter)
        self.current_userlist.setObjectName("current_userlist")
        self.horizontalLayout_6.addWidget(self.current_userlist)
        spacerItem14 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.progressBar_2 = QtWidgets.QProgressBar(bruteforce_attack_dialog)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_5.addWidget(self.progressBar_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        spacerItem15 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.current_password = QtWidgets.QLabel(bruteforce_attack_dialog)
        self.current_password.setAlignment(QtCore.Qt.AlignCenter)
        self.current_password.setObjectName("current_password")
        self.horizontalLayout_5.addWidget(self.current_password)
        spacerItem16 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.progressBar = QtWidgets.QProgressBar(bruteforce_attack_dialog)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        spacerItem17 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        spacerItem18 = QtWidgets.QSpacerItem(27, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem18)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.attack_error_label = QtWidgets.QLabel(bruteforce_attack_dialog)
        self.attack_error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.attack_error_label.setObjectName("attack_error_label")
        self.verticalLayout_8.addWidget(self.attack_error_label)
        spacerItem19 = QtWidgets.QSpacerItem(23, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem19)
        self.attack_status_textBrowser = QtWidgets.QTextBrowser(bruteforce_attack_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attack_status_textBrowser.sizePolicy().hasHeightForWidth())
        self.attack_status_textBrowser.setSizePolicy(sizePolicy)
        self.attack_status_textBrowser.setObjectName("attack_status_textBrowser")
        self.verticalLayout_8.addWidget(self.attack_status_textBrowser)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem20 = QtWidgets.QSpacerItem(158, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem20)
        self.attack_button = QtWidgets.QPushButton(bruteforce_attack_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.attack_button.sizePolicy().hasHeightForWidth())
        self.attack_button.setSizePolicy(sizePolicy)
        self.attack_button.setObjectName("attack_button")
        self.horizontalLayout_10.addWidget(self.attack_button)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem21)
        self.stop_attack_button = QtWidgets.QPushButton(bruteforce_attack_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.stop_attack_button.sizePolicy().hasHeightForWidth())
        self.stop_attack_button.setSizePolicy(sizePolicy)
        self.stop_attack_button.setObjectName("stop_attack_button")
        self.horizontalLayout_10.addWidget(self.stop_attack_button)
        spacerItem22 = QtWidgets.QSpacerItem(188, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem22)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)

        self.retranslateUi(bruteforce_attack_dialog)
        QtCore.QMetaObject.connectSlotsByName(bruteforce_attack_dialog)


    def retranslateUi(self, bruteforce_attack_dialog):
        bruteforce_attack_dialog.setWindowTitle(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "Database Bruteforce ", None))
        self.groupBox.setTitle(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "Database Type", None))
        self.mysql_radio.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "MySQL", None))
        self.oracle_radio.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "Oracle", None))
        self.postgres_radio.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "PostgreSQL", None))
        self.mssql_radio.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "MS-SQL", None))
        self.groupBox_3.setTitle(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "Database Connection ", None))
        self.label_2.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "MySQL Server:", None))
        self.attck_server_checkbox.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "MySQL Port:", None))
        self.label_3.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "( Default MySQL port is 3306 TCP )", None))
        self.groupBox_2.setTitle(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "Dictionary Attack Options", None))
        self.userlist_button.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "User List", None))
        self.userlist_details.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "", None))
        self.blank_password_checkbox.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "Attempt blank password", None))
        self.wordlist_button.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "Word List", None))
        self.wordlist_details.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "", None))
        self.stop_attack_button.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "Stop Attack", None))
        self.current_userlist.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "<font color=red>Not Started</font>", None))
        self.current_password.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "<font color=red>Not Started</font>", None))
        self.attack_button.setText(QtCore.QCoreApplication.translate("bruteforce_attack_dialog", "Launch Attack", None))
