import os
from PyQt5 import QtCore, QtGui, QtWidgets

class setting_dialog(object):
    def setupUi(self, setting_dialog):
        setting_dialog.setObjectName("setting_dialog")
        setting_dialog.resize(469, 231)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(setting_dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.database_type_label = QtWidgets.QLabel(setting_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.database_type_label.setFont(font)
        self.database_type_label.setText("")
        self.database_type_label.setObjectName("database_type_label")
        self.horizontalLayout_3.addWidget(self.database_type_label)
        spacerItem2 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.server_name = QtWidgets.QLabel(setting_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.server_name.setFont(font)
        self.server_name.setObjectName("server_name")
        self.verticalLayout_2.addWidget(self.server_name)
        spacerItem4 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.server_port_check = QtWidgets.QCheckBox(setting_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.server_port_check.setFont(font)
        self.server_port_check.setObjectName("server_port_check")
        self.verticalLayout_2.addWidget(self.server_port_check)
        spacerItem5 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.server_connection = QtWidgets.QLineEdit(setting_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.server_connection.setFont(font)
        self.server_connection.setObjectName("server_connection")
        self.verticalLayout.addWidget(self.server_connection)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.server_port = QtWidgets.QLineEdit(setting_dialog)
        self.server_port.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.server_port.setFont(font)
        self.server_port.setObjectName("server_port")
        self.horizontalLayout.addWidget(self.server_port)
        self.default_server_port = QtWidgets.QLabel(setting_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.default_server_port.setFont(font)
        self.default_server_port.setObjectName("default_server_port")
        self.horizontalLayout.addWidget(self.default_server_port)
        spacerItem6 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.buttonBox = QtWidgets.QDialogButtonBox(setting_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(setting_dialog)
        self.buttonBox.accepted.connect(setting_dialog.accept)
        self.buttonBox.rejected.connect(setting_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(setting_dialog)



    def retranslateUi(self, setting_dialog):
        setting_dialog.setWindowTitle(QtCore.QCoreApplication.translate("setting_dialog", '', None))
        self.server_name.setText(QtCore.QCoreApplication.translate("setting_dialog", '', None))
        self.server_port_check.setText(QtCore.QCoreApplication.translate("setting_dialog", '', None))
        self.default_server_port.setText(QtCore.QCoreApplication.translate("setting_dialog", '', None))
