import os
from PyQt5 import QtCore, QtGui, QtWidgets

try:
    from PyQt5 import Qsci, QtWidgets
except:
    pass

class interaction_dialog(object):
    def setupUi(self, interaction_dialog):
        interaction_dialog.setObjectName("interaction_dialog")
        interaction_dialog.resize(1000, 641)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(interaction_dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(interaction_dialog)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("%s/Icons/Database.png"%(os.getcwd())))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.interact_server_name = QtWidgets.QLabel(interaction_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interact_server_name.setFont(font)
        self.interact_server_name.setObjectName("interact_server_name")
        self.verticalLayout.addWidget(self.interact_server_name)
        self.interact_server_connection = QtWidgets.QLabel(interaction_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interact_server_connection.setFont(font)
        self.interact_server_connection.setObjectName("interact_server_connection")
        self.verticalLayout.addWidget(self.interact_server_connection)
        self.label_4 = QtWidgets.QLabel(interaction_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.interact_comboBox = QtWidgets.QComboBox(interaction_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interact_comboBox.setFont(font)
        self.interact_comboBox.setObjectName("interact_comboBox")
        self.verticalLayout_2.addWidget(self.interact_comboBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(interaction_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.interact_browse = QtWidgets.QPushButton(interaction_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interact_browse.setFont(font)
        self.interact_browse.setObjectName("interact_browse")
        self.horizontalLayout_2.addWidget(self.interact_browse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(interaction_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.response_table = QtWidgets.QTableWidget(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.response_table.setFont(font)
        self.response_table.setObjectName("response_table")
        self.response_table.setColumnCount(0)
        self.response_table.setRowCount(0)
        self.horizontalLayout_7.addWidget(self.response_table)
        spacerItem1 = QtWidgets.QSpacerItem(0, 241, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.interact_textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interact_textBrowser.sizePolicy().hasHeightForWidth())
        self.interact_textBrowser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interact_textBrowser.setFont(font)
        self.interact_textBrowser.setObjectName("interact_textBrowser")
        self.horizontalLayout_8.addWidget(self.interact_textBrowser)
        spacerItem2 = QtWidgets.QSpacerItem(0, 47, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(interaction_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.sqleditor = QtWidgets.QLineEdit()
        #self.sqleditor.setStyleSheet("background-color: red")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sqleditor.sizePolicy().hasHeightForWidth())
        self.sqleditor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.sqleditor.setFont(font)
        self.sqleditor.setToolTip("")
        self.sqleditor.setWhatsThis("")
        self.sqleditor.setObjectName("sqleditor")
        self.horizontalLayout_11.addWidget(self.sqleditor)
        spacerItem3 = QtWidgets.QSpacerItem(0, 123, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(0, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.execute_sql_button = QtWidgets.QPushButton(interaction_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execute_sql_button.sizePolicy().hasHeightForWidth())
        self.execute_sql_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.execute_sql_button.setFont(font)
        self.execute_sql_button.setObjectName("execute_sql_button")
        self.horizontalLayout_4.addWidget(self.execute_sql_button)
        self.tables_button = QtWidgets.QPushButton(interaction_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tables_button.sizePolicy().hasHeightForWidth())
        self.tables_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tables_button.setFont(font)
        self.tables_button.setObjectName("tables_button")
        self.horizontalLayout_4.addWidget(self.tables_button)
        self.save_report_button = QtWidgets.QPushButton(interaction_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_report_button.sizePolicy().hasHeightForWidth())
        self.save_report_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.save_report_button.setFont(font)
        self.save_report_button.setObjectName("save_report_button")
        self.horizontalLayout_4.addWidget(self.save_report_button)
        self.close_interact_button = QtWidgets.QPushButton(interaction_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_interact_button.sizePolicy().hasHeightForWidth())
        self.close_interact_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.close_interact_button.setFont(font)
        self.close_interact_button.setObjectName("close_interact_button")
        self.horizontalLayout_4.addWidget(self.close_interact_button)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)

        self.retranslateUi(interaction_dialog)
        QtCore.QMetaObject.connectSlotsByName(interaction_dialog)

    def retranslateUi(self, interaction_dialog):
        interaction_dialog.setWindowTitle(QtCore.QCoreApplication.translate("interaction_dialog", "Database Interaction", None))
        self.interact_server_name.setText(QtCore.QCoreApplication.translate("interaction_dialog", "TextLabel", None))
        self.interact_server_connection.setText(QtCore.QCoreApplication.translate("interaction_dialog", "TextLabel", None))
        self.label_4.setText(QtCore.QCoreApplication.translate("interaction_dialog", "TextLabel", None))
        self.interact_browse.setText(QtCore.QCoreApplication.translate("interaction_dialog", "Browse", None))
        self.groupBox.setTitle(QtCore.QCoreApplication.translate("interaction_dialog", "SQL Server Response", None))
        self.groupBox_2.setTitle(QtCore.QCoreApplication.translate("interaction_dialog", "SQL Query  (Press F5 to execute)", None))
        self.execute_sql_button.setText(QtCore.QCoreApplication.translate("interaction_dialog", "Execute SQL Script", None))
        self.tables_button.setText(QtCore.QCoreApplication.translate("interaction_dialog", "Show Tables", None))
        self.save_report_button.setText(QtCore.QCoreApplication.translate("interaction_dialog", "Save Report", None))
        self.close_interact_button.setText(QtCore.QCoreApplication.translate("interaction_dialog", "Close Connection", None))
