import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 620)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("%s/Icons/Database.png"%(os.getcwd())), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.database_Gbox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.database_Gbox.setFont(font)
        self.database_Gbox.setObjectName("database_Gbox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.database_Gbox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mysql_button = QtWidgets.QPushButton(self.database_Gbox)
        self.mysql_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("%s/Icons/mysql_logo.png"%(os.getcwd())), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mysql_button.setIcon(icon1)
        self.mysql_button.setIconSize(QtCore.QSize(100, 100))
        self.mysql_button.setObjectName("mysql_button")
        self.verticalLayout_2.addWidget(self.mysql_button)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.oracle_status = QtWidgets.QLabel(self.database_Gbox)
        self.oracle_status.setAlignment(QtCore.Qt.AlignCenter)
        self.oracle_status.setObjectName("oracle_status")
        self.horizontalLayout_3.addWidget(self.oracle_status)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(34, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.oracle_button = QtWidgets.QPushButton(self.database_Gbox)
        self.oracle_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("%s/Icons/Oracle_Logo.png"%(os.getcwd())), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.oracle_button.setIcon(icon2)
        self.oracle_button.setIconSize(QtCore.QSize(100, 100))
        self.oracle_button.setObjectName("oracle_button")
        self.verticalLayout_3.addWidget(self.oracle_button)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mysql_status = QtWidgets.QLabel(self.database_Gbox)
        self.mysql_status.setAlignment(QtCore.Qt.AlignCenter)
        self.mysql_status.setObjectName("mysql_status")
        self.horizontalLayout.addWidget(self.mysql_status)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(34, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.postgresql = QtWidgets.QPushButton(self.database_Gbox)
        self.postgresql.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/postgresql.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.postgresql.setIcon(icon3)
        self.postgresql.setIconSize(QtCore.QSize(93, 96))
        self.postgresql.setObjectName("postgresql")
        self.verticalLayout_8.addWidget(self.postgresql)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sql_status = QtWidgets.QLabel(self.database_Gbox)
        self.sql_status.setAlignment(QtCore.Qt.AlignCenter)
        self.sql_status.setObjectName("sql_status")
        self.horizontalLayout_2.addWidget(self.sql_status)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sqlite_button = QtWidgets.QPushButton(self.database_Gbox)
        self.sqlite_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("%s/Icons/SQLite_Logo-3e5453f0a4c3e6f5.png"%(os.getcwd())), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sqlite_button.setIcon(icon4)
        self.sqlite_button.setIconSize(QtCore.QSize(100, 100))
        self.sqlite_button.setObjectName("sqlite_button")
        self.verticalLayout.addWidget(self.sqlite_button)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.postgresql_label = QtWidgets.QLabel(self.database_Gbox)
        self.postgresql_label.setAlignment(QtCore.Qt.AlignCenter)
        self.postgresql_label.setObjectName("postgresql_label")
        self.horizontalLayout_4.addWidget(self.postgresql_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(34, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sql_button = QtWidgets.QPushButton(self.database_Gbox)
        self.sql_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("%s/Icons/sql-server-2008-logo.png"%(os.getcwd())), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sql_button.setIcon(icon5)
        self.sql_button.setIconSize(QtCore.QSize(100, 100))
        self.sql_button.setObjectName("sql_button")
        self.verticalLayout_6.addWidget(self.sql_button)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sqlite_label = QtWidgets.QLabel(self.database_Gbox)
        self.sqlite_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sqlite_label.setObjectName("sqlite_label")
        self.horizontalLayout_7.addWidget(self.sqlite_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(197, 9, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.verticalLayout_11.addWidget(self.database_Gbox)
        self.AdminGbox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.AdminGbox.setFont(font)
        self.AdminGbox.setObjectName("AdminGbox")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.AdminGbox)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(self.AdminGbox)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icons/administrator.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.AdminGbox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.AdminGbox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(38, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_7.addItem(spacerItem6)
        self.horizontalLayout_13.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.username_linedit = QtWidgets.QLineEdit(self.AdminGbox)
        self.username_linedit.setObjectName("username_linedit")
        self.verticalLayout_5.addWidget(self.username_linedit)
        spacerItem7 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.password_linedit = QtWidgets.QLineEdit(self.AdminGbox)
        self.password_linedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_linedit.setObjectName("password_linedit")
        self.verticalLayout_4.addWidget(self.password_linedit)
        spacerItem8 = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.login_button = QtWidgets.QPushButton(self.AdminGbox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_button.setIcon(icon)
        self.login_button.setIconSize(QtCore.QSize(28, 27))
        self.login_button.setCheckable(True)
        self.login_button.setFlat(False)
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_11.addWidget(self.login_button)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.password_manager_button = QtWidgets.QPushButton(self.AdminGbox)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icons/manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.password_manager_button.setIcon(icon7)
        self.password_manager_button.setIconSize(QtCore.QSize(28, 27))
        self.password_manager_button.setObjectName("password_manager_button")
        self.horizontalLayout_11.addWidget(self.password_manager_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.verticalLayout_11.addWidget(self.AdminGbox)
        spacerItem11 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem11)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.brutefore_database = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brutefore_database.sizePolicy().hasHeightForWidth())
        self.brutefore_database.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.brutefore_database.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icons/bruteforce.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brutefore_database.setIcon(icon8)
        self.brutefore_database.setIconSize(QtCore.QSize(47, 40))
        self.brutefore_database.setObjectName("brutefore_database")
        self.horizontalLayout_9.addWidget(self.brutefore_database)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.verticalLayout_11.addWidget(self.groupBox)
        spacerItem14 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem14)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", "HexorBase", None))
        self.database_Gbox.setTitle(QtCore.QCoreApplication.translate("MainWindow", "Database Servers", None))
        self.oracle_status.setText(QtCore.QCoreApplication.translate("MainWindow", "<font color=red>API is not Installed</font>", None))
        self.mysql_status.setText(QtCore.QCoreApplication.translate("MainWindow", "<font color=red>API not Installed</font>", None))
        self.sql_status.setText(QtCore.QCoreApplication.translate("MainWindow", "<font color=red>API not Installed</font>", None))
        self.postgresql_label.setText(QtCore.QCoreApplication.translate("MainWindow", "<font color=red>API not Installed</font>", None))
        self.sqlite_label.setText(QtCore.QCoreApplication.translate("MainWindow", "<font color=red>API not Installed</font>", None))
        self.AdminGbox.setTitle(QtCore.QCoreApplication.translate("MainWindow", "Administration", None))
        self.label_2.setText(QtCore.QCoreApplication.translate("MainWindow", "Username:", None))
        self.label_3.setText(QtCore.QCoreApplication.translate("MainWindow", "Password:", None))
        self.brutefore_database.setText(QtCore.QCoreApplication.translate("MainWindow", " Bruteforce Database Servers", None))
        self.login_button.setText(QtCore.QCoreApplication.translate("MainWindow", " Lock as Default Login", None))
        self.password_manager_button.setText(QtCore.QCoreApplication.translate("MainWindow", "Password Manager", None))
        self.groupBox.setTitle(QtCore.QCoreApplication.translate("MainWindow", "Audit Database Servers ", None))
        self.label_4.setText(QtCore.QCoreApplication.translate("MainWindow", "Written by: Saviour Emmanuel Ekiko", None))
        self.label_5.setText(QtCore.QCoreApplication.translate("MainWindow", "Report bugs at: savioboyz@rocketmail.com", None))
