import os
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_password_manager(object):
    def setupUi(self, password_manager):
        password_manager.setObjectName("password_manager")
        password_manager.resize(484, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        password_manager.setWindowIcon(icon)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(password_manager)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(password_manager)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(password_manager)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(18, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.password_manager_table = QtWidgets.QTableWidget(password_manager)
        self.password_manager_table.setObjectName("password_manager_table")
        self.password_manager_table.setColumnCount(2)
        self.password_manager_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.password_manager_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.password_manager_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.password_manager_table)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.password_save_changes = QtWidgets.QPushButton(password_manager)
        self.password_save_changes.setObjectName("password_save_changes")
        self.verticalLayout_4.addWidget(self.password_save_changes)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(268, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.use_credential = QtWidgets.QPushButton(password_manager)
        self.use_credential.setObjectName("use_credential")
        self.horizontalLayout.addWidget(self.use_credential)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.inser_credential = QtWidgets.QPushButton(password_manager)
        self.inser_credential.setObjectName("inser_credential")
        self.horizontalLayout.addWidget(self.inser_credential)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.delete_credential = QtWidgets.QPushButton(password_manager)
        self.delete_credential.setObjectName("delete_credential")
        self.horizontalLayout.addWidget(self.delete_credential)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)

        self.retranslateUi(password_manager)
        QtCore.QMetaObject.connectSlotsByName(password_manager)

    def retranslateUi(self, password_manager):
        password_manager.setWindowTitle(QtCore.QCoreApplication.translate("password_manager", "Password Manager", None))
        self.label.setText(QtCore.QCoreApplication.translate("password_manager", "Select or add database credentials to be used for the login process of the  database", None))
        self.label_2.setText(QtCore.QCoreApplication.translate("password_manager", "login phase. Passwords are displayed as plain text.", None))
        self.password_manager_table.horizontalHeaderItem(0).setText(QtCore.QCoreApplication.translate("password_manager", "Username", None))
        self.password_manager_table.horizontalHeaderItem(1).setText(QtCore.QCoreApplication.translate("password_manager", "Password", None))
        self.password_save_changes.setText(QtCore.QCoreApplication.translate("password_manager", "Save Changes", None))
        self.use_credential.setText(QtCore.QCoreApplication.translate("password_manager", "  Use Selected Credential  ", None))
        self.inser_credential.setText(QtCore.QCoreApplication.translate("password_manager", "   Insert New Login Credential  ", None))
        self.delete_credential.setText(QtCore.QCoreApplication.translate("password_manager", "  Delete Credential  ", None))
